# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleLotCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_max', models.IntegerField()),
                ('inspection_level', models.CharField(max_length=3)),
                ('sample_code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SampleSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(max_length=25)),
                ('sample_size', models.IntegerField()),
                ('aql', models.DecimalField(decimal_places=1, max_digits=100)),
                ('accept', models.IntegerField()),
                ('reject', models.IntegerField()),
            ],
        ),
    ]
