# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sampling_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplesize',
            name='sample_code_letter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sampling_plan.SampleLotCode'),
            preserve_default=False,
        ),
    ]
