# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling_plan', '0002_samplesize_sample_code_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplesize',
            name='test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
