# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampling_plan', '0003_samplesize_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplesize',
            name='test',
        ),
    ]
